FROM rust:1.86-slim-bookworm AS builder

WORKDIR /build

COPY native/rinha-lb/Cargo.toml ./native/rinha-lb/
COPY native/rinha-lb/.cargo ./native/rinha-lb/.cargo
COPY native/rinha-lb/src ./native/rinha-lb/src

RUN cargo build --release --manifest-path native/rinha-lb/Cargo.toml --bin rinha-lb

FROM gcr.io/distroless/cc-debian12

COPY --from=builder /build/native/rinha-lb/target/release/rinha-lb /rinha-lb

ENTRYPOINT ["/rinha-lb"]
