services:
  app1:
    image: ghcr.io/gustavoqnt/gustavoqntsrv:scm-epoll-local
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app1
    environment:
      IVF_BLOCKS_PATH: "/app/resources/references.ivf-blocks-K4096.bin"
      IVF_BBOX_SEED: "1"
      IVF_BBOX_VISIT_CAP: "32"
      SOCK_PATH: /run/rinha/api1.sock
      USE_SCM_EPOLL: "1"
      EPOLL_IDLE_US: "40"
      RINHA_USE_AVX2: "1"
      MALLOC_ARENA_MAX: "1"
    volumes:
      - rinha-sock:/run/rinha
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  app2:
    image: ghcr.io/gustavoqnt/gustavoqntsrv:scm-epoll-local
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app2
    environment:
      IVF_BLOCKS_PATH: "/app/resources/references.ivf-blocks-K4096.bin"
      IVF_BBOX_SEED: "1"
      IVF_BBOX_VISIT_CAP: "32"
      SOCK_PATH: /run/rinha/api2.sock
      USE_SCM_EPOLL: "1"
      EPOLL_IDLE_US: "40"
      RINHA_USE_AVX2: "1"
      MALLOC_ARENA_MAX: "1"
    volumes:
      - rinha-sock:/run/rinha
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "160MB"

  lb:
    image: ghcr.io/gustavoqnt/gustavoqntlb:scm-epoll-local
    build:
      context: .
      dockerfile: Dockerfile.lb
    environment:
      PORT: "9999"
      UPSTREAMS: "/run/rinha/api1.sock.ctrl,/run/rinha/api2.sock.ctrl"
      WORKERS: "1"
      BACKLOG: "65535"
    volumes:
      - rinha-sock:/run/rinha
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

volumes:
  rinha-sock:
