[package]
name = "rinha_lb"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rinha-lb"
path = "src/main.rs"

[target.'cfg(target_os = "linux")'.dependencies]
monoio = { version = "0.2", default-features = false, features = ["iouring"] }
libc = "0.2"
socket2 = "0.5"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
opt-level = 3
panic = "abort"
overflow-checks = false
incremental = false
